# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bedrock_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bedrock_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x65\x64rock_service.proto\x12\x07\x62\x65\x64rock\"%\n\x13GenerateTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\".\n\x14GenerateTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2]\n\x0e\x42\x65\x64rockService\x12K\n\x0cGenerateText\x12\x1c.bedrock.GenerateTextRequest\x1a\x1d.bedrock.GenerateTextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bedrock_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATETEXTREQUEST']._serialized_start=34
  _globals['_GENERATETEXTREQUEST']._serialized_end=71
  _globals['_GENERATETEXTRESPONSE']._serialized_start=73
  _globals['_GENERATETEXTRESPONSE']._serialized_end=119
  _globals['_BEDROCKSERVICE']._serialized_start=121
  _globals['_BEDROCKSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
